version: '2'
services:
    postgres:
        image: postgres:10.12
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=15sl02tt
    wildfly:
        image: wild
        ports:
            - "8080:8080"
        environment:
            - POSTGRES_PORT_5432_TCP_ADDR=postgres
            - POSTGRES_PORT_5432_TCP_PORT=5432
            - POSTGRES_ENV_POSTGRES_USERNAME=postgres
            - POSTGRES_ENV_POSTGRES_PASSWORD=15sl02tt
        volumes:
            - ./deployments:/opt/jboss/wildfly/standalone/deployments
            - ./deployments:/opt/tmp
        depends_on:
            - postgres
volumes:
    deployments: